import type { ICountryPalette } from '../theme/types.ts'
import { escapeXml, hex } from './format.ts'

const attribute = (name: string, options: Record<string, string>) => {
  const optionTags = Object.entries(options)
    .map(([key, value]) => `<option name="${key}" value="${value}"/>`)
    .join('')

  return `    <option name="${name}"><value>${optionTags}</value></option>`
}

export const createColorSchemeXml = (palette: ICountryPalette) => {
  const attributes = [
    attribute('DEFAULT_BLOCK_COMMENT', { FOREGROUND: hex(palette.muted), FONT_TYPE: '2' }),
    attribute('DEFAULT_BRACES', { FOREGROUND: hex(palette.foreground) }),
    attribute('DEFAULT_CLASS_NAME', { FOREGROUND: hex(palette.tertiary) }),
    attribute('DEFAULT_CONSTANT', { FOREGROUND: hex(palette.tertiary) }),
    attribute('DEFAULT_FUNCTION_CALL', { FOREGROUND: hex(palette.accent) }),
    attribute('DEFAULT_IDENTIFIER', { FOREGROUND: hex(palette.foreground) }),
    attribute('DEFAULT_INSTANCE_METHOD', { FOREGROUND: hex(palette.accentAlt) }),
    attribute('DEFAULT_INVALID_STRING_ESCAPE', {
      FOREGROUND: hex(palette.error),
      EFFECT_COLOR: hex(palette.error),
      ERROR_STRIPE_COLOR: hex(palette.error)
    }),
    attribute('DEFAULT_KEYWORD', { FOREGROUND: hex(palette.primary) }),
    attribute('DEFAULT_LINE_COMMENT', { FOREGROUND: hex(palette.muted), FONT_TYPE: '2' }),
    attribute('DEFAULT_NUMBER', { FOREGROUND: hex(palette.tertiary) }),
    attribute('DEFAULT_OPERATION_SIGN', { FOREGROUND: hex(palette.primary) }),
    attribute('DEFAULT_PARAMETER', { FOREGROUND: hex(palette.secondary) }),
    attribute('DEFAULT_STRING', { FOREGROUND: hex(palette.secondary) })
  ].join('\n')

  return `<!-- Generated by src/jetbrains/build.ts. -->
<scheme name="${escapeXml(palette.name)}" version="142" parent_scheme="Darcula">
  <colors>
    <option name="CARET_COLOR" value="${hex(palette.primary)}"/>
    <option name="CARET_ROW_COLOR" value="050505"/>
    <option name="GUTTER_BACKGROUND" value="000000"/>
    <option name="INDENT_GUIDE" value="222222"/>
    <option name="LINE_NUMBERS_COLOR" value="${hex(palette.muted)}"/>
    <option name="RIGHT_MARGIN_COLOR" value="222222"/>
    <option name="SELECTION_BACKGROUND_COLOR" value="${hex(palette.primary)}"/>
  </colors>
  <attributes>
${attributes}
  </attributes>
</scheme>
`
}
