import type { ICountryPalette } from '../theme/types.ts'
import type { IPackageManifest } from './types.ts'
import { escapeXml } from './format.ts'

const pluginId = 'com.pedrohrferreira.rodsThemes'
const pluginName = 'Rods Themes'

export const createPluginXml = (
  packageJson: IPackageManifest,
  palettes: ICountryPalette[]
) => {
  const themeProviders = palettes
    .map(
      (palette) =>
        `    <themeProvider id="rods-themes.${escapeXml(palette.id)}" path="/themes/${escapeXml(palette.id)}-neon-black.theme.json"/>`
    )
    .join('\n')

  return `<!-- Generated by src/jetbrains/build.ts. -->
<idea-plugin>
  <id>${pluginId}</id>
  <name>${pluginName}</name>
  <version>${escapeXml(packageJson.version)}</version>
  <idea-version since-build="241"/>
  <vendor url="${escapeXml(packageJson.author?.url ?? packageJson.homepage ?? '')}">${escapeXml(packageJson.author?.name ?? 'PedroHRFerreira')}</vendor>

  <description><![CDATA[
    <p>${escapeXml(packageJson.description)}</p>
    <p>Dark/neon themes inspired by World Cup national teams, preserving absolute black backgrounds and bright country accents.</p>
  ]]></description>

  <depends>com.intellij.modules.platform</depends>

  <extensions defaultExtensionNs="com.intellij">
${themeProviders}
  </extensions>
</idea-plugin>
`
}
