import type { ICountryPalette } from './types.ts'

const alpha = (color: string, opacity: string) => `${color}${opacity}`

export const createUiColors = (palette: ICountryPalette): Record<string, string> => ({
  focusBorder: alpha(palette.primary, '99'),
  foreground: palette.foreground,
  descriptionForeground: palette.muted,
  errorForeground: palette.error,
  'editor.background': '#000000',
  'editor.foreground': palette.foreground,
  'editorCursor.foreground': palette.primary,
  'editor.selectionBackground': alpha(palette.primary, '44'),
  'editor.inactiveSelectionBackground': alpha(palette.primary, '22'),
  'editor.lineHighlightBackground': alpha(palette.primary, '10'),
  'editorLineNumber.foreground': palette.muted,
  'editorLineNumber.activeForeground': palette.secondary,
  'editorGutter.background': '#000000',
  'editorGutter.addedBackground': palette.success,
  'editorGutter.modifiedBackground': palette.warning,
  'editorGutter.deletedBackground': palette.error,
  'editorOverviewRuler.addedForeground': alpha(palette.success, 'DD'),
  'editorOverviewRuler.modifiedForeground': alpha(palette.warning, 'DD'),
  'editorOverviewRuler.deletedForeground': alpha(palette.error, 'DD'),
  'minimapGutter.addedBackground': palette.success,
  'minimapGutter.modifiedBackground': palette.warning,
  'minimapGutter.deletedBackground': palette.error,
  'diffEditor.insertedTextBackground': alpha(palette.success, '22'),
  'diffEditor.removedTextBackground': alpha(palette.error, '22'),
  'editorIndentGuide.background1': '#222222',
  'editorIndentGuide.activeBackground1': palette.primary,
  'sideBar.background': '#000000',
  'sideBar.foreground': palette.foreground,
  'activityBar.background': '#000000',
  'activityBar.foreground': palette.primary,
  'activityBar.activeBorder': palette.secondary,
  'statusBar.background': '#000000',
  'statusBar.foreground': palette.secondary,
  'titleBar.activeBackground': '#000000',
  'titleBar.activeForeground': palette.foreground,
  'editorGroupHeader.tabsBackground': '#000000',
  'tab.activeBackground': '#050505',
  'tab.activeForeground': palette.secondary,
  'tab.inactiveBackground': '#000000',
  'tab.inactiveForeground': palette.muted,
  'panel.background': '#000000',
  'terminal.background': '#000000',
  'terminal.foreground': palette.foreground,
  'terminalCursor.foreground': palette.primary,
  'button.background': palette.primary,
  'button.foreground': '#000000',
  'button.hoverBackground': palette.accent,
  'input.background': '#050505',
  'input.border': alpha(palette.primary, '99'),
  'dropdown.background': '#050505',
  'list.activeSelectionBackground': alpha(palette.primary, '33'),
  'list.highlightForeground': palette.tertiary,
  'gitDecoration.modifiedResourceForeground': palette.warning,
  'gitDecoration.addedResourceForeground': palette.success,
  'gitDecoration.deletedResourceForeground': palette.error
})
